### ISSUE TITLE
RAPID-001 (Module Setup)

### ISSUE THREAD

**Issue by ghost** [Booternerd/Team-Auto#1]
[Communication/Status/Motion Modules]

Feature: Setup module skeletons for all modules using example code.

Files:
- MTRN4230_Server_Sample
- MTRN4230_Move_Sample
- MTRN4230_IO_Sample

Notes:
- This issue is BACKLOG.
- No added functionality required yet.

**Comment by DJTeebS** [comment]
Status: Initiated

**Comment by DJTeebS** [comment]
Status: Testing

**Comment by DJTeebS** [comment]
Status: Initiated

**Comment by DJTeebS** [comment]
Status: Testing

**Comment by ghost** [comment]
Status: Started

**Comment by ghost** [comment]
Status: Ready for Testing

Comment:
- Imported sample files
- Renamed modules
- Renamed main functions

**Comment by ghost** [comment]
Status: Tested/Merged
