### ISSUE TITLE
RAPID-002 (Polling Strings)

### ISSUE THREAD

**Issue by ghost** [Booternerd/Team-Auto#2]
[Communications Module]

Feature: Poll strings sent from Matlab.

Notes:
- This issue is BACKLOG.

**Comment by DJTeebS** [comment]
Status: Initiated

**Comment by DJTeebS** [comment]
Status: Testing

**Comment by DJTeebS** [comment]
Status: Initiated
Date: ?

**Comment by ghost** [comment]
Status: Started

**Comment by ghost** [comment]
Status: Ready for Testing

Comment:
- Added infinite loop for polling strings
- Receives string of team member name from Matlab
- Sends string of team member position to Matlab
- Default for test case bounces string back to Matlab

**Comment by ghost** [comment]
Status: Tested/Merged
